=== BaseAdresseNationale/ban-plateforme/__coding-test/ban-json-schema/schemas/ban-diff-grouped.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://ban.local/schemas/ban-diff-grouped.schema.json",
  "title": "BAN diff (group√©)",
  "type": "object",
  "required": [
    "meta",
    "created",
    "updated",
    "disabled"
  ],
  "additionalProperties": false,
  "properties": {
    "meta": {
      "type": "object",
      "required": [
        "from",
        "to",
        "generatedAt"
      ],
      "additionalProperties": false,
      "properties": {
        "from": {
          "type": "string",
          "format": "date-time"
        },
        "to": {
          "type": "string",
          "format": "date-time"
        },
        "generatedAt": {
          "type": "string",
          "format": "date-time"
        }
      }
    },
    "created": {
      "$ref": "#/$defs/collections"
    },
    "disabled": {
      "$ref": "#/$defs/collections"
    },
    "updated": {
      "type": "object",
      "required": [
        "communes",
        "odonymes",
        "adresses"
      ],
      "additionalProperties": false,
      "properties": {
        "communes": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/updatedCommune"
          }
        },
        "odonymes": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/updatedOdonyme"
          }
        },
        "adresses": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/updatedAdresse"
          }
        }
      }
    }
  },
  "$defs": {
    "collections": {
      "type": "object",
      "required": [
        "communes",
        "odonymes",
        "adresses"
      ],
      "additionalProperties": false,
      "properties": {
        "communes": {
          "type": "array",
          "items": {
            "$ref": "https://ban.local/schemas/common.defs.schema.json#/$defs/commune"
          }
        },
        "odonymes": {
          "type": "array",
          "items": {
            "$ref": "https://ban.local/schemas/common.defs.schema.json#/$defs/odonyme"
          }
        },
        "adresses": {
          "type": "array",
          "items": {
            "$ref": "https://ban.local/schemas/common.defs.schema.json#/$defs/adresse"
          }
        }
      }
    },
    "updatedCommune": {
      "type": "array",
      "minItems": 2,
      "maxItems": 2,
      "prefixItems": [
        {
          "$ref": "https://ban.local/schemas/common.defs.schema.json#/$defs/commune"
        },
        {
          "$ref": "https://ban.local/schemas/common.defs.schema.json#/$defs/commune"
        }
      ],
      "items": false,
      "$comment": "Tuple [after, before]."
    },
    "updatedOdonyme": {
      "type": "array",
      "minItems": 2,
      "maxItems": 2,
      "prefixItems": [
        {
          "$ref": "https://ban.local/schemas/common.defs.schema.json#/$defs/odonyme"
        },
        {
          "$ref": "https://ban.local/schemas/common.defs.schema.json#/$defs/odonyme"
        }
      ],
      "items": false,
      "$comment": "Tuple [after, before]."
    },
    "updatedAdresse": {
      "type": "array",
      "minItems": 2,
      "maxItems": 2,
      "prefixItems": [
        {
          "$ref": "https://ban.local/schemas/common.defs.schema.json#/$defs/adresse"
        },
        {
          "$ref": "https://ban.local/schemas/common.defs.schema.json#/$defs/adresse"
        }
      ],
      "items": false,
      "$comment": "Tuple [after, before]."
    }
  }
}

=== BaseAdresseNationale/ban-plateforme/__coding-test/ban-json-schema/examples/ban-diff-grouped.example.json
{
  "meta": {
    "from": "2025-12-01T00:00:00Z",
    "to": "2025-12-17T00:00:00Z",
    "generatedAt": "2025-12-17T23:17:55Z"
  },
  "created": {
    "communes": [],
    "odonymes": [
      {
        "idOdonyme": "3e8704e8-32c1-4a85-a074-0377a31435b2",
        "idCommune": "7c7b44ff-9198-4258-b9b2-ae3165201658",
        "cleInterop": "64125_NOUVELLEVOIE",
        "nom": {
          "codeLangue": "fra",
          "nom": "Nouvelle voie"
        },
        "nomsMultilinguesOdonyme": [
          {
            "codeLangue": "fra",
            "nom": "Nouvelle voie"
          }
        ]
      }
    ],
    "adresses": [
      {
        "position": {
          "type": "entree",
          "geometry": {
            "type": "Point",
            "coordinates": [
              -1.554321,
              43.4367891
            ]
          }
        },
        "idAdresseCommunale": "279b25c8-3ca2-4ffe-9dab-1d9bb3a83f06",
        "cleInterop": "64125_NOUVELLEVOIE_7",
        "idVoiePlaceLieudit": "3e8704e8-32c1-4a85-a074-0377a31435b2",
        "idLieuditComplementaire": null,
        "idCommune": "7c7b44ff-9198-4258-b9b2-ae3165201658",
        "codeInseeCommuneHistorique": null,
        "certification": true,
        "positionsComplementaires": [],
        "dateDebut": "2025-01-01",
        "dateDerniereMiseAJour": "2025-12-17T23:17:55Z",
        "sources": [
          "mairie"
        ],
        "parcellesCadastrales": [],
        "codePostal": "64210",
        "numero": 7,
        "indiceRepetition": null
      }
    ]
  },
  "updated": {
    "communes": [],
    "odonymes": [],
    "adresses": [
      [
        {
          "position": {
            "type": "entree",
            "geometry": {
              "type": "Point",
              "coordinates": [
                -1.554321,
                43.4367891
              ]
            }
          },
          "idAdresseCommunale": "71bc89c8-0637-49e9-a5cf-ede3730a8bdc",
          "cleInterop": "64125_RUEDELAMER_12",
          "idVoiePlaceLieudit": "31036d18-9890-4611-b955-ef1e95de48d1",
          "idLieuditComplementaire": null,
          "idCommune": "7c7b44ff-9198-4258-b9b2-ae3165201658",
          "codeInseeCommuneHistorique": null,
          "certification": true,
          "positionsComplementaires": [],
          "dateDebut": "2025-01-01",
          "dateDerniereMiseAJour": "2025-12-17T23:17:55Z",
          "sources": [
            "mairie"
          ],
          "parcellesCadastrales": [],
          "codePostal": "64500",
          "numero": 12,
          "indiceRepetition": null
        },
        {
          "position": {
            "type": "entree",
            "geometry": {
              "type": "Point",
              "coordinates": [
                -1.554321,
                43.4367891
              ]
            }
          },
          "idAdresseCommunale": "71bc89c8-0637-49e9-a5cf-ede3730a8bdc",
          "cleInterop": "64125_RUEDELAMER_12",
          "idVoiePlaceLieudit": "31036d18-9890-4611-b955-ef1e95de48d1",
          "idLieuditComplementaire": null,
          "idCommune": "7c7b44ff-9198-4258-b9b2-ae3165201658",
          "codeInseeCommuneHistorique": null,
          "certification": true,
          "positionsComplementaires": [],
          "dateDebut": "2025-01-01",
          "dateDerniereMiseAJour": "2025-12-17T11:56:03Z",
          "sources": [
            "mairie"
          ],
          "parcellesCadastrales": [],
          "codePostal": "64210",
          "numero": 12,
          "indiceRepetition": null
        }
      ]
    ]
  },
  "disabled": {
    "communes": [],
    "odonymes": [],
    "adresses": [
      {
        "position": {
          "type": "entree",
          "geometry": {
            "type": "Point",
            "coordinates": [
              -1.5541203,
              43.4367002
            ]
          }
        },
        "idAdresseCommunale": "fb0bfe79-e722-4eda-b91e-c2d53ac2df84",
        "cleInterop": "64125_RUEDELAMER_14_BIS",
        "idVoiePlaceLieudit": "31036d18-9890-4611-b955-ef1e95de48d1",
        "idLieuditComplementaire": null,
        "idCommune": "7c7b44ff-9198-4258-b9b2-ae3165201658",
        "codeInseeCommuneHistorique": null,
        "certification": true,
        "positionsComplementaires": [],
        "dateDebut": "2025-01-01",
        "dateDerniereMiseAJour": "2025-12-17T11:56:03Z",
        "sources": [
          "mairie"
        ],
        "parcellesCadastrales": [],
        "codePostal": "64210",
        "numero": 14,
        "indiceRepetition": "B"
      }
    ]
  }
}

=== BaseAdresseNationale/ban-plateforme/__coding-test/ban-json-schema/examples/ban-diff-grouped.edge-cases.json
{
  "meta": {
    "from": "2025-12-01T00:00:00Z",
    "to": "2025-12-17T00:00:00Z",
    "generatedAt": "2025-12-17T23:29:43Z"
  },
  "created": {
    "communes": [],
    "odonymes": [
      {
        "idOdonyme": "4d86bbf4-b689-4626-83a2-90cdbf17a053",
        "idCommune": "c3cf9dd0-7784-47d1-a631-970510b2d103",
        "cleInterop": "2B037_TOPONYME0",
        "nom": {
          "codeLangue": "fra",
          "nom": "Toponyme Zéro"
        },
        "nomsMultilinguesOdonyme": [
          {
            "codeLangue": "fra",
            "nom": "Toponyme Zéro"
          }
        ]
      }
    ],
    "adresses": [
      {
        "position": {
          "type": "entree",
          "geometry": {
            "type": "Point",
            "coordinates": [
              180.0,
              90.0
            ]
          }
        },
        "idAdresseCommunale": "dd488f8f-d426-4f8a-8e6e-ec53f174b197",
        "cleInterop": "2B037_TOPONYMEEDGE_0",
        "idVoiePlaceLieudit": "4d86bbf4-b689-4626-83a2-90cdbf17a053",
        "idLieuditComplementaire": null,
        "idCommune": "c3cf9dd0-7784-47d1-a631-970510b2d103",
        "codeInseeCommuneHistorique": null,
        "certification": true,
        "positionsComplementaires": [],
        "dateDebut": "2025-01-01",
        "dateDerniereMiseAJour": "2025-12-17T23:29:43Z",
        "sources": [
          "import-ban"
        ],
        "parcellesCadastrales": [
          "2B037000A0123"
        ],
        "codePostal": "20230",
        "indiceRepetition": null,
        "numero": 0
      }
    ]
  },
  "updated": {
    "communes": [],
    "odonymes": [
      [
        {
          "idOdonyme": "06ae8496-70da-4507-b288-c97c5e595cc7",
          "idCommune": "c3cf9dd0-7784-47d1-a631-970510b2d103",
          "cleInterop": "2B037_TOPONYMEA",
          "nom": {
            "codeLangue": "fr-gallo",
            "nom": "Toponim Modifié"
          },
          "nomsMultilinguesOdonyme": [
            {
              "codeLangue": "fr-gallo",
              "nom": "Toponim Modifié"
            }
          ]
        },
        {
          "idOdonyme": "06ae8496-70da-4507-b288-c97c5e595cc7",
          "idCommune": "c3cf9dd0-7784-47d1-a631-970510b2d103",
          "cleInterop": "2B037_TOPONYMEA",
          "nom": {
            "codeLangue": "fra",
            "nom": "Toponyme A"
          },
          "nomsMultilinguesOdonyme": [
            {
              "codeLangue": "fra",
              "nom": "Toponyme A"
            },
            {
              "codeLangue": "fr-gallo",
              "nom": "Toponim A"
            }
          ]
        }
      ]
    ],
    "adresses": [
      [
        {
          "position": {
            "type": "entree",
            "geometry": {
              "type": "Point",
              "coordinates": [
                -180.0,
                -90.0
              ]
            }
          },
          "idAdresseCommunale": "10674b01-399d-4571-8d04-89315ea0aa6e",
          "cleInterop": "2B037_TOPONYMEEDGE_12_BIS",
          "idVoiePlaceLieudit": "06ae8496-70da-4507-b288-c97c5e595cc7",
          "idLieuditComplementaire": null,
          "idCommune": "c3cf9dd0-7784-47d1-a631-970510b2d103",
          "codeInseeCommuneHistorique": null,
          "certification": false,
          "positionsComplementaires": [],
          "dateDebut": "2025-01-01",
          "dateDerniereMiseAJour": "2025-12-17T23:29:43Z",
          "sources": [
            "import-ban"
          ],
          "parcellesCadastrales": [],
          "codePostal": "20230",
          "indiceRepetition": null,
          "numero": 12
        },
        {
          "position": {
            "type": "entree",
            "geometry": {
              "type": "Point",
              "coordinates": [
                -180.0,
                -90.0
              ]
            }
          },
          "idAdresseCommunale": "680a48dd-706a-4cb4-a1ef-1660c37d55c0",
          "cleInterop": "2B037_TOPONYMEEDGE_x",
          "idVoiePlaceLieudit": "06ae8496-70da-4507-b288-c97c5e595cc7",
          "idLieuditComplementaire": null,
          "idCommune": "c3cf9dd0-7784-47d1-a631-970510b2d103",
          "codeInseeCommuneHistorique": null,
          "certification": false,
          "positionsComplementaires": [],
          "dateDebut": "2025-01-01",
          "dateDerniereMiseAJour": "2025-12-17T23:29:43Z",
          "sources": [
            "import-ban"
          ],
          "parcellesCadastrales": [],
          "codePostal": "20230",
          "indiceRepetition": null
        }
      ]
    ]
  },
  "disabled": {
    "communes": [],
    "odonymes": [
      {
        "idOdonyme": "06ae8496-70da-4507-b288-c97c5e595cc7",
        "idCommune": "c3cf9dd0-7784-47d1-a631-970510b2d103",
        "cleInterop": "2B037_TOPONYMEA",
        "nom": {
          "codeLangue": "fra",
          "nom": "Toponyme A"
        },
        "nomsMultilinguesOdonyme": [
          {
            "codeLangue": "fra",
            "nom": "Toponyme A"
          },
          {
            "codeLangue": "fr-gallo",
            "nom": "Toponim A"
          }
        ]
      }
    ],
    "adresses": [
      {
        "position": {
          "type": "entree",
          "geometry": {
            "type": "Point",
            "coordinates": [
              -180.0,
              -90.0
            ]
          }
        },
        "idAdresseCommunale": "dce15fc7-ccf1-45ec-85e3-a8276fbd28c5",
        "cleInterop": "2B037_TOPONYMEEDGE_99998_A",
        "idVoiePlaceLieudit": "06ae8496-70da-4507-b288-c97c5e595cc7",
        "idLieuditComplementaire": null,
        "idCommune": "c3cf9dd0-7784-47d1-a631-970510b2d103",
        "codeInseeCommuneHistorique": null,
        "certification": false,
        "positionsComplementaires": [],
        "dateDebut": "2025-01-01",
        "dateDerniereMiseAJour": "2025-12-17T23:29:43Z",
        "sources": [
          "mairie",
          "ign"
        ],
        "parcellesCadastrales": [],
        "codePostal": "20230",
        "indiceRepetition": "A",
        "numero": 99998
      }
    ]
  }
}
